// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiT10dEOsz16dZNpIgCU3TxsUrv0jlfLg',
    appId: '1:773306749946:web:c348acc6e960730eb70a43',
    messagingSenderId: '773306749946',
    projectId: 'social-media-flutter-84338',
    authDomain: 'social-media-flutter-84338.firebaseapp.com',
    storageBucket: 'social-media-flutter-84338.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jNt10MduIIzaYyNAqR8W9khm2BLBne0',
    appId: '1:773306749946:android:a9e6d5ac6f0cf1ceb70a43',
    messagingSenderId: '773306749946',
    projectId: 'social-media-flutter-84338',
    storageBucket: 'social-media-flutter-84338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByd-MqnjXwIgw_hHgJpBEGTLEFb4IRagQ',
    appId: '1:773306749946:ios:576c19cbbdfe6bb6b70a43',
    messagingSenderId: '773306749946',
    projectId: 'social-media-flutter-84338',
    storageBucket: 'social-media-flutter-84338.appspot.com',
    iosBundleId: 'com.example.socialMediaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByd-MqnjXwIgw_hHgJpBEGTLEFb4IRagQ',
    appId: '1:773306749946:ios:e86176d115c6a6ecb70a43',
    messagingSenderId: '773306749946',
    projectId: 'social-media-flutter-84338',
    storageBucket: 'social-media-flutter-84338.appspot.com',
    iosBundleId: 'com.example.socialMediaFlutter.RunnerTests',
  );
}
